apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["sleep 100"]
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  volumes:
  - name: scratch-volume
    emptyDir:
      sizeLimit: 50Mi

