apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - image: nginx:stable-alpine
          name: nginx
